-- 組裝測試 LOG 共用資料表
-- 請在 Supabase SQL Editor 執行一次，讓不同電腦共用上傳的分析結果。

create table if not exists public.assembly_log_batches (
    id text primary key,
    line text not null default 'ASSY',
    file_name text not null,
    uploaded_at timestamptz not null default now(),
    encoding text,
    line_count integer,
    parsed_line_count integer,
    ignored_count integer,
    unclassified_count integer,
    buckets jsonb not null default '{}'::jsonb
);

create index if not exists assembly_log_batches_line_uploaded_idx
    on public.assembly_log_batches (line, uploaded_at desc);

-- 目前系統使用 Supabase anon key，且既有資料表採用相同的公開 CRUD 模式。
alter table public.assembly_log_batches disable row level security;
grant select, insert, update, delete on public.assembly_log_batches to anon, authenticated;

-- 未知 LOG 訊息與不良項目的對應表
create table if not exists public.assembly_log_mappings (
    id bigint generated by default as identity primary key,
    line text not null default 'ASSY',
    log_message text not null,
    defect_name text not null,
    created_at timestamptz not null default now(),
    unique (line, log_message)
);

create index if not exists assembly_log_mappings_line_idx
    on public.assembly_log_mappings (line, created_at desc);

alter table public.assembly_log_mappings disable row level security;
grant select, insert, update, delete on public.assembly_log_mappings to anon, authenticated;
grant usage, select on sequence public.assembly_log_mappings_id_seq to anon, authenticated;

-- 立即讓 Supabase API 重新載入新資料表結構。
notify pgrst, 'reload schema';
